vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        articles:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        categories:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        tags:
            uri_prefix: /images/tags
            upload_destination: '%kernel.project_dir%/public/images/tags'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

#        inject_on_load: false
#        delete_on_update: true
#        delete_on_remove: true
